export enum ActionTypes {
  APP__SET_USER = 0x00,
  APP__NOTIFY = 0x01,
  APP__HIDE_NOTIFICATION = 0x02,
  APP__OPEN_DIALOG = 0x03,

  DOMAIN__SET_DOMAINS = 0x10,
  DOMAIN__SET_DOMAIN = 0x11,
  DOMAIN__SET_RECORDS = 0x12,
  DOMAIN__SET_MOD_PURPOSE = 0x13,
  DOMAIN__SET_EDITING_RECORD = 0x14,
  DOMAIN__RESET_EDITING_RECORD = 0x15,
  DOMAIN__DELETE_DOMAINS = 0x16,

  CONFIRM__SET_CALLBACK = 0x20,
  CONFIRM__SET_SU_CALLBACK = 0x21,
}
