export enum ActionTypes {
  APP__SET_USER = 0x00,
  APP__NOTIFY = 0x01,
  APP__HIDE_NOTIFICATION = 0x02,
  APP__OPEN_DIALOG = 0x03,

  DOMAIN__SET_DOMAINS = 0x10,
  DOMAIN__SET_DOMAIN = 0x11,
  DOMAIN__SET_RECORDS = 0x12,

  CONFIRM__SET_CALLBACK = 0x20,
}
